EMRS/Controllers/MedicalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EMRS.Models;
using EMRS.Filters;

namespace EMRS.Controllers
{
    [Authorize]
    [InitializeSimpleMembership]
    public class MedicalController : Controller
    {
        private HospitalContext db = new HospitalContext();

        //
        // GET: /Medical/

        public ActionResult Index(string searchString)
        {
            if (User.IsInRole("AttendingPhysician"))
            {
                AttendingPhysician self = db.AttendingPhysicians.FirstOrDefault(
                    item => item.UserName.Equals(User.Identity.Name));
                if (self == null)
                {
                    return HttpNotFound();
                }
                var tmp = db.MedicalRecords.Where(
                    item => item.Physician.UserId == self.UserId);
                if (!String.IsNullOrEmpty(searchString))
                {
                    string[] keywords = searchString.Split(new char[] { ' ', '\t' });
                    foreach (string key in keywords)
                    {
                        tmp = tmp.Where(s => s.Patient.Name.Contains(key));
                    }
                }
                var medicalRecords = tmp.Select(item => new ListMedicalRecordModel
                    {
                        MedicalRecordID = item.MedicalRecordID,
                        PatientName = item.Patient.Name,
                        PhysicianName = item.Physician.Name,
                        StartTime = item.CreatedTime,
                        UnderTreatment = !item.IsFinished
                    });
                return View(medicalRecords);
            }
            else if (User.IsInRole("Patient"))
            {
                Patient self = db.Patients.FirstOrDefault(
                    item => item.UserName.Equals(User.Identity.Name));
                if (self == null)
                {
                    return HttpNotFound();
                }
                var tmp = db.MedicalRecords.Where(
                    item => item.Patient.UserId == self.UserId);
                if (!String.IsNullOrEmpty(searchString))
                {
                    string[] keywords = searchString.Split(new char[] { ' ', '\t' });
                    foreach (string key in keywords)
                    {
                        tmp = tmp.Where(s => s.Physician.Name.Contains(key));
                    }
                }
                var medicalRecords = tmp.Select(item => new ListMedicalRecordModel
                    {
                        MedicalRecordID = item.MedicalRecordID,
                        PatientName = item.Patient.Name,
                        PhysicianName = item.Physician.Name,
                        StartTime = item.CreatedTime,
                        UnderTreatment = !item.IsFinished
                    });
                return View(medicalRecords);
            }
            return HttpNotFound();
        }

        //
        // GET: /Medical/Details/5

        public ActionResult Details(int id = 0)
        {
            MedicalRecord medicalrecord = db.MedicalRecords.Find(id);
            if (medicalrecord == null)
            {
                return HttpNotFound();
            }
            return View(medicalrecord);
        }

        //
        // GET: /Medical/Create/5

        public ActionResult Create(int id = 0)
        {
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(new CreateMedicalRecordModel {
                PatientID = id,
                PatientName = patient.Name,
                Physicians = new SelectList(
                    db.AttendingPhysicians,
                    "UserID", "Name", 
                    db.AttendingPhysicians.First())
            });
        }

        //
        // POST: /Medical/Create

        [HttpPost]
        public ActionResult Create(CreateMedicalRecordModel medicalrecordInfo)
        {
            if (ModelState.IsValid)
            {
                MedicalRecord medicalrecord = new MedicalRecord {
                    Comment = medicalrecordInfo.Comment,
                    IsFinished = false,
                    CreatedTime = DateTime.Now,
                    Physician = db.AttendingPhysicians.Find(medicalrecordInfo.PhysicianID),
                    Patient = db.Patients.Find(medicalrecordInfo.PatientID)
                };
                db.MedicalRecords.Add(medicalrecord);
                db.SaveChanges();
                return RedirectToAction("Index", "Patient");
            }

            return View(medicalrecordInfo);
        }

        //
        // GET: /Medical/Attach

        public ActionResult Attach(int id = 0)
        {
            MedicalRecord medicalRecord = db.MedicalRecords.Find(id);
            if (medicalRecord == null)
            {
                return HttpNotFound();
            }
            return View(new AttachTreatmentRecordModel
            {
                MedicalRecordID = medicalRecord.MedicalRecordID,
                PatientName = medicalRecord.Patient.Name,
                Comment = medicalRecord.Comment,
                CreatedTime = medicalRecord.CreatedTime,
                IsFinished = false
            });
        }

        //
        // POST: /Medical/Attach

        [HttpPost]
        public ActionResult Attach(AttachTreatmentRecordModel treatmentRecord)
        {
            if (ModelState.IsValid)
            {
                MedicalRecord medicalrecord = db.MedicalRecords.Find(
                    treatmentRecord.MedicalRecordID);
                medicalrecord.TreatmentRecords.Add(new TreatmentRecord
                {
                    CreatedTime = DateTime.Now,
                    Description = treatmentRecord.Description
                });
                medicalrecord.IsFinished = treatmentRecord.IsFinished;
                db.Entry(medicalrecord).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = treatmentRecord.MedicalRecordID });
            }

            return View(treatmentRecord);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

EMRS/Views/Medical/Attach.cshtml
@model EMRS.Models.AttachTreatmentRecordModel

@{
    ViewBag.Title = "Assign Doctor";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@Html.DisplayNameFor(model => model.PatientName) : @Html.DisplayFor(model => model.PatientName)</h1>
                
                <h2>@Html.DisplayFor(model => model.CreatedTime)</h2>
            </hgroup>
            <p>
                @Html.DisplayFor(model => model.Comment)
            </p>
        </div>
    </section>
}

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>TreatmentRecord</legend>

        @Html.HiddenFor(model => model.MedicalRecordID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsFinished)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsFinished)
            @Html.ValidationMessageFor(model => model.IsFinished)
        </div>

        <p>
            <input type="submit" value="Attach" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to Details", "Details", new { id = Model.MedicalRecordID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EMRS/Views/Medical/Create.cshtml
@model EMRS.Models.CreateMedicalRecordModel

@{
    ViewBag.Title = "Assign Doctor";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>MedicalRecord</legend>
        
        @Html.HiddenFor(model => model.PatientID)

        <div class="editor-label">
            @Html.LabelFor(model => model.PatientName)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.PatientName, new { @readonly="readonly", @disabled="true" })
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PhysicianID)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.PhysicianID, Model.Physicians)
            @Html.ValidationMessageFor(model => model.PhysicianID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comment)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Comment)
            @Html.ValidationMessageFor(model => model.Comment)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Patient")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EMRS/Views/Medical/Details.cshtml
@model EMRS.Models.MedicalRecord

@{
    ViewBag.Title = "Medical Record Details";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                @if (User.IsInRole("AttendingPhysician"))
                {
                <h1>@Html.DisplayNameFor(model => model.Patient) : @Html.DisplayFor(model => model.Patient.Name)</h1>
                }
                else if (User.IsInRole("Patient"))
                {
                <h1>@Html.DisplayNameFor(model => model.Physician) : @Html.DisplayFor(model => model.Physician.Name)</h1>
                }
                
                <h2>@Html.DisplayFor(model => model.CreatedTime)</h2>
            </hgroup>
            <p>
                @Html.DisplayFor(model => model.Comment)
            </p>
        </div>
    </section>
}
<ol class="round">
    @foreach (var item in Model.TreatmentRecords) {
    <li class="none">
        <h5>@Html.DisplayFor(modelItem => item.CreatedTime)</h5>
        @Html.DisplayFor(modelItem => item.Description)
    </li>
    }
</ol>
<p>
    @if (User.IsInRole("AttendingPhysician") && !Model.IsFinished)
    {
    @Html.ActionLink("Attach Medical Record", "Attach", new { id= Model.MedicalRecordID })
    }
    @Html.ActionLink("Back to List", "Index")
</p>

EMRS/Views/Medical/Index.cshtml
@model IEnumerable<EMRS.Models.ListMedicalRecordModel>

@{
    ViewBag.Title = "Medical Record";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<p>
    @Html.ActionLink("Show All", "Index")
    @using (Html.BeginForm("Index", "Medical", FormMethod.Get))
    {    
         <p> Name: @Html.TextBox("SearchString")
         <input type="submit" value="Search" /></p>
    }
</p>
<table>
    <tr>
        @if (User.IsInRole("AttendingPhysician"))
        {
        <th>
            @Html.DisplayNameFor(model => model.PatientName)
        </th>
        }
        @if (User.IsInRole("Patient"))
        {
        <th>
            @Html.DisplayNameFor(model => model.PhysicianName)
        </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnderTreatment)
        </th>
        <th></th>
    </tr>
@foreach (var item in Model) {
    <tr>
        @if (User.IsInRole("AttendingPhysician"))
        {
        <td>
            @Html.DisplayFor(modelItem => item.PatientName)
        </td>
        }
        @if (User.IsInRole("Patient"))
        {
        <td>
            @Html.DisplayFor(modelItem => item.PhysicianName)
        </td>
        }
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnderTreatment)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.MedicalRecordID })
        </td>
    </tr>
}

</table>